file_origen = ""
ruta_destino = ""
ruta_destino_excel = ""
regex_numero = "[0-9]"
fecha_seteada = ""
checkbox = False
checkbox_falla = False

aeropuertos = (
    "AEP",
    "BAR",
    "BCA",
    "CAT",
    "CBA",
    "CHP",
    "CRR",
    "CRV",
    "DIL",
    "DOZ",
    "DRY",
    "ECA",
    "ERE",
    "ESQ",
    "EZE RWY 11 29",  
    "EZE RWY 17 35",  
    "EZE VOR",  
    "FDO",
    "FSA",
    "GAL",
    "GBE",
    "GNR",
    "GPI",
    "GRA",
    "GUA",
    "IGU",
    "JUA",
    "JUJ",
    "LAR",
    "LYE",
    "MDP",
    "MJZ",
    "MLG",
    "NEU",
    "NIN",
    "OEL",
    "OSA",
    "PAL",
    "PAR",
    "POS",
    "PTA",
    "ROS",
    "RTA",
    "RYD",
    "SAL",
    "SDE",
    "SIS",
    "SJU",
    "SNT",
    "SRA",
    "SRC",
    "SVO",
    "TRC",
    "TRE",
    "TRH",
    "TUC",
    "UIS",
    "USH",
    "VIE",
)
sistema = "ILS","LI","VOR","NDB"
folio = "LH","PARAMETROS","PARAMETROS I","PARAMETROS II","DME ILS PARAMETROS","DME VOR PARAMETROS","CHECK LIST I","CHECK LIST II","POUT","GROUND CHECK",
region = "FIR CBA","FIR CRV","FIR DOZ","FIR EZE","FIR SIS"